/**
 * QR Scanner
 * A Fragment which can scan a QR code containing an event id and redirects to the
 * corresponding event overview.
 * Last Modified: 2026-03-25 by Grace MacKenzie
 *
 *<p>
 *     TODO: cite these:
 *          https://reintech.io/blog/implementing-android-app-qr-code-scanner
 *     TODO: test this fragment
 *          see https://calvin.my/posts/how-to-test-qr-code-scanning-with-android-emulator-camera
 *</p>
 *
 * @author Grace MacKenzie
 * @since 2026-03-25
 */
package com.example.eventlottery;

import android.Manifest;
import android.os.Bundle;

import androidx.activity.result.ActivityResultLauncher;
import androidx.activity.result.contract.ActivityResultContracts;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;

import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.Toast;

import com.google.firebase.firestore.FirebaseFirestore;
import com.journeyapps.barcodescanner.DecoratedBarcodeView;

/**
 * A Fragment which can scan a QR code containing an event id and redirects to the
 * corresponding event overview.
 */
public class QrScannerFragment extends Fragment {

    // ATTRIBUTES

    private final ActivityResultLauncher<String> requestCameraPermission =
            registerForActivityResult(new ActivityResultContracts.RequestPermission(), isGranted -> {
                if (isGranted) {
                    startScanner();
                } else {
                    Toast.makeText(getContext(), "Camera permission denied", Toast.LENGTH_LONG).show();
                }
            });

    private DecoratedBarcodeView barcodeView;

    // CONSTRUCTORS

    public QrScannerFragment() {
        // Required empty public constructor
    }

    // OVERRIDDEN FUNCTIONS

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_qr_scanner, container, false);
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        barcodeView = view.findViewById(R.id.barcode_scanner);

        // BIND BACK BUTTON
        Button cancelButton = view.findViewById(R.id.cancel_button);
        cancelButton.setOnClickListener( v -> {
            // navigate back to home page
            HomePageFragment fragment = new HomePageFragment();
            requireActivity().getSupportFragmentManager()
                    .beginTransaction()
                    .replace(R.id.fragment_container, fragment)
                    .commit();
        });

        // START SCANNING
        requestCameraPermission.launch(Manifest.permission.CAMERA);
    }

    @Override
    public void onResume() {
        super.onResume();
        barcodeView.resume();
    }

    @Override
    public void onPause() {
        barcodeView.pause();
        super.onPause();
    }

    // METHODS

    /**
     * A factory method to create a new QrScannerFragment.
     * @return A new instance of the QrScannerFragment.
     */
    public static QrScannerFragment newInstance() {
        return new QrScannerFragment();
    }

    // HELPER METHODS

    private void startScanner() {
        barcodeView.decodeContinuous(result -> {
            // result is the decoded string from the QR code
            String qrText = result.getText();
            // Log.d("QR_DEBUG", "Raw QR text: [" + qrText + "]");

            if (qrText != null) {
                // Stop scanning so it doesn't fire repeatedly
                barcodeView.pause();

                // Handle the result
                if (!isFirebaseId(qrText)) {
                    Toast.makeText(requireContext(), R.string.error_invalid_qr_code, Toast.LENGTH_SHORT).show();
                    barcodeView.resume();
                } else {
                    handleFirebaseId(qrText);
                }
            }
        });
    }

    /**
     * A helper function to detect whether a string is an id generated by firebase.
     * (firebase ids are 20 chars long, contain digits 0-9, and contain upper and
     * lowercase letters a-z)
     * @param text The string to detect
     * @return True if text fits the format of a firebase id, False otherwise
     */
    private boolean isFirebaseId(String text) {
        return text != null && text.matches("^[A-Za-z0-9]{20}$");
    }

    private void handleFirebaseId(String eventId) {
        FirebaseFirestore db = FirebaseFirestore.getInstance();
        db.collection("events")
                .document(eventId)
                .get()
                .addOnSuccessListener(document -> {
                    if (document.exists()) {
                        // Valid event ID
                        goToEventOverview(eventId);
                    } else {
                        // Not found in Firestore
                        Toast.makeText(getContext(), "Event not found", Toast.LENGTH_SHORT).show();
                        barcodeView.resume();
                    }
                })
                .addOnFailureListener(e -> {
                    Toast.makeText(getContext(), "Error checking event", Toast.LENGTH_SHORT).show();
                    barcodeView.resume();
                });
    }

    private void goToEventOverview(String eventId) {
        EventOverviewFragment fragment = new EventOverviewFragment();
        Bundle bundle = new Bundle();
        bundle.putString("eventId", eventId);
        fragment.setArguments(bundle);
        requireActivity().getSupportFragmentManager()
                .beginTransaction()
                .replace(R.id.fragment_container, fragment)
                .commit();
    }
}